name: 'Test'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  latest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run package
      - run: printenv

      - uses: ./
        with:
          secrets: TESTSECRET

      - run: printenv

      - if: ${{ github.ref == 'refs/heads/main' && env.TARGET_BRANCH != 'main' }}
        run: |
          echo "Assertion failed for TARGET_BRANCH: $TARGET_BRANCH != main"
          exit 1

      - if: ${{ github.ref == 'refs/heads/main' && env.TARGET_BRANCH_U != 'MAIN' }}
        run: |
          echo "Assertion failed for TARGET_BRANCH_U: $TARGET_BRANCH_U != MAIN"
          exit 1

      - if: ${{ env.TESTSECRET_NAME != format('TESTSECRET_{0}', env.TARGET_BRANCH_U) }}
        run: |
          echo "Assertion failed for TESTSECRET_NAME: $TESTSECRET_NAME != TESTSECRET_MAIN"
          exit 1
